# Generated by Django 3.1.6 on 2021-02-01 15:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('link', models.CharField(max_length=200, verbose_name='لینک')),
                ('img', models.ImageField(upload_to='ad_pic', verbose_name='عکس')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.advertiser', verbose_name='تبلیغ دهنده')),
            ],
        ),
    ]
