# Generated by Django 3.1.6 on 2021-02-08 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('link', models.CharField(max_length=200, verbose_name='لینک')),
                ('img', models.ImageField(upload_to='ad_pic/', verbose_name='عکس')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('clicks', models.IntegerField(default=0, verbose_name='کلیک ها')),
                ('views', models.IntegerField(default=0, verbose_name='بازدید ها')),
            ],
        ),
    ]
