# Generated by Django 3.1.6 on 2021-02-08 14:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_ad_advertiser'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('ck', 'click'), ('vi', 'view')], max_length=2)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان رویداد')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertising.ad', verbose_name='تبلیغ')),
            ],
        ),
    ]
