# Generated by Django 3.1.6 on 2021-02-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0004_auto_20210208_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='views',
        ),
    ]
