# Generated by Django 3.1.6 on 2021-02-09 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210208_2131'),
        ('advertising', '0005_auto_20210208_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='user.advertiser', verbose_name='تبلیغ دهنده'),
        ),
    ]
